import Mathlib

/-!
# Rank-15 common-root hyperplane slicing: statement target

This module is an **UNPROVED STATEMENT TARGET** for
`experimental/notes/l2/rank15_common_root_hyperplane_slicing.md`. It records
the deployed normalized state, the restricted-domain primitivity condition,
the common-root trigger, and the two exact conclusions of
`R15-HYP14-ROOT-SLICE` without claiming a Lean proof.

The Markdown theorem is mathematically proved by reduction to the integrated
rank-14 affine-section recurrence. The definitions below only make its formal
statement available for future work. They eliminate no state, leave nullities
`1,...,13` unpaid, prove no unconditional rank-15 list bound, and do not change
the official score `0/2`.
-/

open scoped Classical
open Polynomial

noncomputable section

namespace GrandeFinale
namespace Rank15CommonRootHyperplaneSlicing

set_option autoImplicit false

universe u v

variable {D : Type u} {F : Type v}
variable [Fintype D] [DecidableEq D]
variable [Field F] [Fintype F] [DecidableEq F]

def baseFieldPrime : ℕ := 2130706433
def evaluationDomainSize : ℕ := 2097152
def codeDimension : ℕ := 1048576
def agreementThreshold : ℕ := 1116047
def paidQuotientCeiling : ℕ := 4985
def violatorRootDeduction : ℕ := 4986
def rank14FiberBound : ℕ := 20008483
def rank15SliceBound : ℕ := baseFieldPrime * rank14FiberBound
def oneRowTarget : ℕ := 274854110496187592

/-- Evaluate a polynomial on the residual domain. -/
def evalWord (points : D → F) (Q : F[X]) : D → F :=
  fun x ↦ Q.eval (points x)

/-- Number of residual coordinates where `Q` agrees with the received word. -/
def agreementCount (points : D → F) (received : D → F) (Q : F[X]) : ℕ :=
  (Finset.univ.filter fun x ↦ evalWord points Q x = received x).card

/-- Number of listed points in the exact affine flat. -/
def listedCount (points : D → F) (received : D → F) (a : ℕ)
    (calA : Finset F[X]) : ℕ :=
  (calA.filter fun Q ↦ a ≤ agreementCount points received Q).card

/-- Residual evaluation points at which every direction in `J` vanishes. -/
def commonRootCount (points : D → F) (J : Submodule F F[X]) : ℕ :=
  (Finset.univ.filter fun x ↦ ∀ w ∈ J, evalWord points w x = 0).card

/-- The finite set `calA` is exactly the affine coset `Q0 + W`. -/
def ExactAffineFlat (Q0 : F[X]) (W : Submodule F F[X])
    (calA : Finset F[X]) : Prop :=
  ∀ Q, Q ∈ calA ↔ Q - Q0 ∈ W

/-- Every polynomial in the affine flat has degree strictly below `kA`. -/
def DegreeBounded (kA : ℕ) (calA : Finset F[X]) : Prop :=
  ∀ Q ∈ calA, Q.natDegree < kA

/-- The polynomial ideal generated by `W` is the unit ideal: `gcd(W) = 1`. -/
def PolynomialGCDOne (W : Submodule F F[X]) : Prop :=
  Ideal.span (W : Set F[X]) = ⊤

/--
Restricted-domain consequence of polynomial-gcd primitivity: every residual
evaluation functional on `W` is nonzero.
-/
def PrimitiveOn (points : D → F) (W : Submodule F F[X]) : Prop :=
  ∀ x, ∃ w ∈ W, evalWord points w x ≠ 0

/--
**UNPROVED STATEMENT TARGET.** The gcd-one hypothesis implies the nonzero
evaluation condition on the restricted residual domain.
-/
def gcdOneImpliesPrimitiveOnTarget (points : D → F)
    (W : Submodule F F[X]) : Prop :=
  PolynomialGCDOne W → PrimitiveOn points W

/-- Exact normalized rank-15 state used by the slicing theorem. -/
def NormalizedRank15State (points : D → F) (u c : ℕ) (Q0 : F[X])
    (W : Submodule F F[X]) (calA : Finset F[X]) : Prop :=
  Fintype.card F = baseFieldPrime ∧
    Fintype.card D = evaluationDomainSize - u ∧
    u ≤ agreementThreshold ∧
    u + c ≤ codeDimension ∧
    c ≤ 152 ∧
    Function.Injective points ∧
    Module.finrank F W = 15 ∧
    ExactAffineFlat Q0 W calA ∧
    DegreeBounded (codeDimension - u - c) calA ∧
    PolynomialGCDOne W

/--
**UNPROVED STATEMENT TARGET.** A rank-14 direction hyperplane with at least
`k_A - 4,985` common roots forces the exact base-field fiber bound
`M <= 42,632,203,442,671,139`.
-/
def rootSliceTheoremTarget (points : D → F) (received : D → F)
    (u c : ℕ) (Q0 : F[X]) (W J : Submodule F F[X])
    (calA : Finset F[X]) : Prop :=
  let kA := codeDimension - u - c
  let a := agreementThreshold - u
  NormalizedRank15State points u c Q0 W calA →
    J ≤ W →
    Module.finrank F J = 14 →
    kA - paidQuotientCeiling ≤ commonRootCount points J →
    listedCount points received a calA ≤ rank15SliceBound

/--
**UNPROVED STATEMENT TARGET.** Every target violator obeys the exact negated
trigger `r_J <= k_A - 4,986` for each rank-14 direction hyperplane `J`.
-/
def violatorRootCapTarget (points : D → F) (received : D → F)
    (u c : ℕ) (Q0 : F[X]) (W J : Submodule F F[X])
    (calA : Finset F[X]) : Prop :=
  let kA := codeDimension - u - c
  let a := agreementThreshold - u
  NormalizedRank15State points u c Q0 W calA →
    J ≤ W →
    Module.finrank F J = 14 →
    oneRowTarget < listedCount points received a calA →
    commonRootCount points J ≤ kA - violatorRootDeduction

end Rank15CommonRootHyperplaneSlicing
end GrandeFinale
