#!/usr/bin/env python3
"""Macaulay2 syzygy proxy for the M1 a=327 random-matroid rank-rigidity front."""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
from pathlib import Path
from typing import Any


SOURCE_COMMIT = "c3bb743"
DEPENDENCY_DATA = Path("experimental/data/m1_a327_dependency_engineered_rank_feedback.json")
OUTPUT_DATA = Path("experimental/data/m1_a327_random_matroid_syzygy_rigidity_proxy.json")
M2_SCRIPT_PATH = Path("experimental/scripts/m2_m1_a327_random_matroid_syzygy_rigidity_proxy.m2")

ROOT = Path(__file__).resolve().parents[2]
DEPENDENCY_SCRIPT = ROOT / "experimental/scripts/scan_m1_a327_dependency_engineered_rank_feedback.py"

PROXY_PRIME = 12289


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


dependency = load_module("dependency_engineered_rank_feedback", DEPENDENCY_SCRIPT)
functional = dependency.functional


def load_json(path: Path) -> dict[str, Any]:
    with path.open() as handle:
        return json.load(handle)


def rank_mod_prime(rows: list[list[int]], ncols: int, prime: int = PROXY_PRIME) -> int:
    matrix = [[value % prime for value in row] for row in rows if any(value % prime for value in row)]
    rank = 0
    for col in range(ncols):
        pivot = None
        for row_idx in range(rank, len(matrix)):
            if matrix[row_idx][col] % prime:
                pivot = row_idx
                break
        if pivot is None:
            continue
        matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
        inv = pow(matrix[rank][col], -1, prime)
        matrix[rank] = [(value * inv) % prime for value in matrix[rank]]
        for row_idx in range(len(matrix)):
            if row_idx == rank or not matrix[row_idx][col] % prime:
                continue
            factor = matrix[row_idx][col] % prime
            matrix[row_idx] = [
                (matrix[row_idx][idx] - factor * matrix[rank][idx]) % prime
                for idx in range(ncols)
            ]
        rank += 1
        if rank == len(matrix) or rank == ncols:
            break
    return rank


def reconstruct_best_profile(record: dict[str, Any]) -> tuple[list[dict[str, Any]], dict[str, Any], dict[str, Any]]:
    best = dict(record["best_candidate"])
    profile_source = next(
        (
            row
            for row in record["dependency_engineered_search"]["profiles"]
            if row.get("template_id") == best["template_id"]
        ),
        None,
    )
    if profile_source is None:
        raise RuntimeError("could not find template profile for best candidate")
    best["template_vectors"] = profile_source["template_vectors"]
    best["total_effective_cost"] = best["effective_cost"]
    classes = functional.functional_classes(best)
    span_rank = functional.rank_mod_p([row["functional"] for row in classes])
    profiles = dependency.dependency_basis_profiles(classes, span_rank=span_rank, random_bases=16)
    target = best["best_proxy"]
    for profile in profiles:
        if (
            profile["basis_id"] == target["basis_id"]
            and profile["basis_class_indices"] == target["basis_class_indices"]
        ):
            return classes, profile, target
    raise RuntimeError("could not reconstruct best dependency profile")


def coefficient_matrix(profile: dict[str, Any]) -> list[list[int]]:
    return [
        [int(value) % PROXY_PRIME for value in row["basis_coordinates"]]
        for row in profile["nonbasis_constraint_detail"]
    ]


def matrix_to_m2_rows(matrix: list[list[int]]) -> str:
    rows = []
    for row in matrix:
        rows.append("{" + ",".join(f"{value}_R" for value in row) + "}")
    return "{" + ",".join(rows) + "}"


def write_m2_script(matrix: list[list[int]], expected_rank: int) -> None:
    text = f"""-- Generated by scan_m1_a327_random_matroid_syzygy_rigidity_proxy.py
R = ZZ/{PROXY_PRIME}[x]
Coeff = matrix({matrix_to_m2_rows(matrix)})
print concatenate("M2_COEFF_ROWS=", toString numRows Coeff)
print concatenate("M2_COEFF_COLS=", toString numColumns Coeff)
print concatenate("M2_COEFF_RANK=", toString rank Coeff)
RightK = gens kernel Coeff
print concatenate("M2_RIGHT_KERNEL_GENS=", toString numColumns RightK)
LeftK = gens kernel transpose Coeff
print concatenate("M2_LEFT_SYZYGY_GENS=", toString numColumns LeftK)
print concatenate("M2_LEFT_SYZYGY_RANK=", toString rank LeftK)
print concatenate("M2_EXPECTED_RANK=", toString {expected_rank})
"""
    M2_SCRIPT_PATH.write_text(text)


def run_m2() -> dict[str, Any]:
    proc = subprocess.run(
        ["M2", "--script", str(M2_SCRIPT_PATH)],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    parsed: dict[str, int] = {}
    for line in proc.stdout.splitlines():
        if line.startswith("M2_") and "=" in line:
            key, value = line.split("=", 1)
            parsed[key] = int(value)
    return {
        "command": ["M2", "--script", str(M2_SCRIPT_PATH)],
        "returncode": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
        "parsed": parsed,
    }


def m2_version() -> str:
    proc = subprocess.run(["M2", "--version"], check=False, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return (proc.stdout or proc.stderr).strip()


def build_record(run_macaulay2: bool) -> dict[str, Any]:
    dependency_record = load_json(DEPENDENCY_DATA)
    classes, profile, proxy = reconstruct_best_profile(dependency_record)
    coeff = coefficient_matrix(profile)
    coeff_rank = rank_mod_prime(coeff, ncols=len(profile["basis_class_indices"]))
    right_kernel_nullity = len(profile["basis_class_indices"]) - coeff_rank
    left_syzygy_dimension = len(coeff) - coeff_rank
    write_m2_script(coeff, expected_rank=coeff_rank)
    m2_result = None
    if run_macaulay2:
        m2_result = run_m2()
    return {
        "track": "INTERLEAVED_LIST",
        "row": "RS[F_17^32,H,256]",
        "denominator": "17^32",
        "agreement_target": 327,
        "source_commit": SOURCE_COMMIT,
        "dependency_engineered": {
            "systems_tested": dependency_record["dependency_engineered_search"]["systems_tested"],
            "proxy_candidates_tested": dependency_record["dependency_engineered_search"]["proxy_candidates_tested"],
            "proxy_basis_profiles_tested": dependency_record["dependency_engineered_search"]["proxy_basis_profiles_tested"],
            "proxy_positive_candidates": dependency_record["dependency_engineered_search"]["proxy_positive_candidates"],
            "best_template_id": dependency_record["dependency_engineered_search"]["best_template_id"],
            "best_proxy_rank": dependency_record["dependency_engineered_search"]["best_proxy_rank"],
            "best_proxy_nullity": dependency_record["dependency_engineered_search"]["best_proxy_nullity"],
            "best_failure_mode": dependency_record["dependency_engineered_search"]["best_failure_mode"],
        },
        "syzygy_proxy": {
            "tool": "Macaulay2",
            "tool_version": m2_version() if run_macaulay2 else None,
            "proxy_field": f"GF({PROXY_PRIME})",
            "template_id": dependency_record["best_candidate"]["template_id"],
            "assignment_strategy": dependency_record["best_candidate"]["assignment_strategy"],
            "basis_id": proxy["basis_id"],
            "basis_class_indices": proxy["basis_class_indices"],
            "functional_classes": len(classes),
            "basis_size": len(profile["basis_class_indices"]),
            "nonbasis_constraints": len(profile["nonbasis_constraint_detail"]),
            "coefficient_matrix_shape": [len(coeff), len(profile["basis_class_indices"])],
            "coefficient_rank_python": coeff_rank,
            "right_kernel_nullity_python": right_kernel_nullity,
            "left_syzygy_dimension_python": left_syzygy_dimension,
            "quotient_matrix_shape": proxy["matrix_shape"],
            "quotient_proxy_rank": proxy["proxy_rank"],
            "quotient_proxy_nullity": proxy["proxy_nullity"],
            "m2_script": str(M2_SCRIPT_PATH),
            "m2_result": m2_result,
            "best_failure_mode": "SYZYGY_PROXY_COEFFICIENT_FULL_RANK_QUOTIENT_FULL_RANK",
        },
        "proof_status": "AUDIT / SYZYGY_RIGIDITY_PROXY / PARTIAL / EXPERIMENTAL",
        "mca_counted": False,
        "not_claimed": [
            "MCA N_bad",
            "protocol soundness",
            "ordinary list decoding beyond stated interleaved-list predicate",
            "global Lambda_mu(C,327) <= 6",
            "exact Lambda_mu",
            "exact delta*_C",
            "global rank rigidity outside the tested proxy front",
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--run-m2", action="store_true")
    args = parser.parse_args()
    record = build_record(run_macaulay2=args.run_m2)
    if args.write:
        OUTPUT_DATA.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n")
    if args.json:
        proxy = record["syzygy_proxy"]
        print(
            json.dumps(
                {
                    "proof_status": record["proof_status"],
                    "coefficient_matrix_shape": proxy["coefficient_matrix_shape"],
                    "coefficient_rank_python": proxy["coefficient_rank_python"],
                    "right_kernel_nullity_python": proxy["right_kernel_nullity_python"],
                    "left_syzygy_dimension_python": proxy["left_syzygy_dimension_python"],
                    "m2_returncode": None if proxy["m2_result"] is None else proxy["m2_result"]["returncode"],
                    "m2_parsed": None if proxy["m2_result"] is None else proxy["m2_result"]["parsed"],
                    "best_failure_mode": proxy["best_failure_mode"],
                },
                indent=2,
                sort_keys=True,
            )
        )
    elif not args.write:
        print("M1_A327_RANDOM_MATROID_SYZYGY_RIGIDITY_PROXY_READY")


if __name__ == "__main__":
    main()
