name = "powersum_rigidity"
defaultTargets = ["PowersumRigidity"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "9a9483a92959bc92bd6a60176dd1fe597298c1f8"

[[lean_lib]]
name = "PowersumRigidity"
